[package]
name = "tui"
version = "0.1.0"
authors = ["Michael Zhang <iptq@protonmail.com>"]

[dependencies]
flubber = { path = "../" }
futures = "0.1"
structopt = "0.2"
termion = "1.5"
tokio = "0.1"
tokio-codec = "0.1"
uuid = { version = "0.7", features = ["v4"] }
