[package]
name = "flubber"
version = "0.1.0"
authors = ["Michael Zhang <iptq@protonmail.com>"]
edition = "2018"

[workspace]
members = ["flubber-irc", "flubber-server"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"